# Generated by Django 4.0.5 on 2023-03-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcommitte', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=255)),
                ('courseCode', models.CharField(max_length=255)),
                ('courseCredit', models.CharField(max_length=255)),
                ('courseTeacher', models.CharField(max_length=255)),
                ('externalTeacher', models.CharField(max_length=255)),
            ],
        ),
    ]
