# Generated by Django 4.0.5 on 2023-03-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcommitte', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='createdExamCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examCommitteeYear', models.CharField(max_length=255)),
                ('examCommitteeStatus', models.CharField(max_length=255)),
            ],
        ),
    ]
