# Generated by Django 4.0.5 on 2023-03-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcommitte', '0005_semister_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='semester',
            field=models.CharField(max_length=255),
        ),
    ]
