# Generated by Django 4.0.5 on 2023-03-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcommitte', '0006_alter_routine_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
